spring.application.name=cricsync

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# CHANGED THIS TO 'create' TO RESET THE DATABASE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Fixes Swagger UI loading over HTTPS on Render
server.forward-headers-strategy=framework
